server:
  port: 7902

spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/GRP2021?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true&allowMultiQueries=true
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: consumer-server

mybatis:
  type-aliases-package: com.grp202116.consumerserver.pojo
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true

logging:
  level:
    com.grp202116.consumerserver.mapper : debug

eureka:
  client:
    healthcheck:
      enabled: true
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:7900/eureka/
  instance:
    prefer-ip-address: true
    instance-id: localhost:${spring.application.name}:${server.port}
    status-page-url: http://localhost:${server.port}/

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 5000