server:
  port: 7900
eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

spring:
  security:
    user:
      name: user
      password: 123456
  application:
    name: eureka-server
  profiles:
    active: "dev"